# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - id: DownloadKeePass
      name: Download KeePass
      uses: smorks/keepass-download-action@v0.0.5
    - name: Extract KeePass
      run: |
          mkdir Build/KeePass
          7z x -o"Build/KeePass" ${{ steps.DownloadKeePass.outputs.filename }} KeePass.exe
    - name: Build
      run: dotnet build --no-restore
    - uses: actions/upload-artifact@v3
      with:
          name: FluentPassFinder
          path: Build/FluentPassFinder
    - name: Zip files
      run: 7z a "FluentPassFinder.zip" .\Build\FluentPassFinder\
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        tag_name: 0.0.0
        prerelease: true
        name: Experimental
        body: Experimental release don't use this version!
        files: "FluentPassFinder.zip"
        
